#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/autoprefixer@10.5.2_postcss@8.5.16/node_modules/autoprefixer/bin/node_modules:/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/autoprefixer@10.5.2_postcss@8.5.16/node_modules/autoprefixer/node_modules:/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/autoprefixer@10.5.2_postcss@8.5.16/node_modules:/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/node_modules"
else
  export NODE_PATH="/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/autoprefixer@10.5.2_postcss@8.5.16/node_modules/autoprefixer/bin/node_modules:/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/autoprefixer@10.5.2_postcss@8.5.16/node_modules/autoprefixer/node_modules:/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/autoprefixer@10.5.2_postcss@8.5.16/node_modules:/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../autoprefixer/bin/autoprefixer" "$@"
else
  exec node  "$basedir/../autoprefixer/bin/autoprefixer" "$@"
fi
@SETLOCAL
@IF NOT DEFINED NODE_PATH (
  @SET "NODE_PATH=C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\autoprefixer@10.5.2_postcss@8.5.16\node_modules\autoprefixer\bin\node_modules;C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\autoprefixer@10.5.2_postcss@8.5.16\node_modules\autoprefixer\node_modules;C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\autoprefixer@10.5.2_postcss@8.5.16\node_modules;C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\node_modules"
) ELSE (
  @SET "NODE_PATH=C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\autoprefixer@10.5.2_postcss@8.5.16\node_modules\autoprefixer\bin\node_modules;C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\autoprefixer@10.5.2_postcss@8.5.16\node_modules\autoprefixer\node_modules;C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\autoprefixer@10.5.2_postcss@8.5.16\node_modules;C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\node_modules;%NODE_PATH%"
)
@IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.exe"  "%~dp0\..\autoprefixer\bin\autoprefixer" %*
) ELSE (
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  node  "%~dp0\..\autoprefixer\bin\autoprefixer" %*
)
#!/usr/bin/env pwsh
$basedir=Split-Path $MyInvocation.MyCommand.Definition -Parent

$exe=""
$pathsep=":"
$env_node_path=$env:NODE_PATH
$new_node_path="C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\autoprefixer@10.5.2_postcss@8.5.16\node_modules\autoprefixer\bin\node_modules;C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\autoprefixer@10.5.2_postcss@8.5.16\node_modules\autoprefixer\node_modules;C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\autoprefixer@10.5.2_postcss@8.5.16\node_modules;C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\node_modules"
if ($PSVersionTable.PSVersion -lt "6.0" -or $IsWindows) {
  # Fix case when both the Windows and Linux builds of Node
  # are installed in the same directory
  $exe=".exe"
  $pathsep=";"
} else {
  $new_node_path="/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/autoprefixer@10.5.2_postcss@8.5.16/node_modules/autoprefixer/bin/node_modules:/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/autoprefixer@10.5.2_postcss@8.5.16/node_modules/autoprefixer/node_modules:/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/autoprefixer@10.5.2_postcss@8.5.16/node_modules:/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/node_modules"
}
if ([string]::IsNullOrEmpty($env_node_path)) {
  $env:NODE_PATH=$new_node_path
} else {
  $env:NODE_PATH="$new_node_path$pathsep$env_node_path"
}

$ret=0
if (Test-Path "$basedir/node$exe") {
  # Support pipeline input
  if ($MyInvocation.ExpectingInput) {
    $input | & "$basedir/node$exe"  "$basedir/../autoprefixer/bin/autoprefixer" $args
  } else {
    & "$basedir/node$exe"  "$basedir/../autoprefixer/bin/autoprefixer" $args
  }
  $ret=$LASTEXITCODE
} else {
  # Support pipeline input
  if ($MyInvocation.ExpectingInput) {
    $input | & "node$exe"  "$basedir/../autoprefixer/bin/autoprefixer" $args
  } else {
    & "node$exe"  "$basedir/../autoprefixer/bin/autoprefixer" $args
  }
  $ret=$LASTEXITCODE
}
$env:NODE_PATH=$env_node_path
exit $ret
#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/eslint@8.57.1/node_modules/eslint/bin/node_modules:/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/eslint@8.57.1/node_modules/eslint/node_modules:/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/eslint@8.57.1/node_modules:/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/node_modules"
else
  export NODE_PATH="/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/eslint@8.57.1/node_modules/eslint/bin/node_modules:/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/eslint@8.57.1/node_modules/eslint/node_modules:/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/eslint@8.57.1/node_modules:/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../eslint/bin/eslint.js" "$@"
else
  exec node  "$basedir/../eslint/bin/eslint.js" "$@"
fi
@SETLOCAL
@IF NOT DEFINED NODE_PATH (
  @SET "NODE_PATH=C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\eslint@8.57.1\node_modules\eslint\bin\node_modules;C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\eslint@8.57.1\node_modules\eslint\node_modules;C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\eslint@8.57.1\node_modules;C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\node_modules"
) ELSE (
  @SET "NODE_PATH=C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\eslint@8.57.1\node_modules\eslint\bin\node_modules;C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\eslint@8.57.1\node_modules\eslint\node_modules;C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\eslint@8.57.1\node_modules;C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\node_modules;%NODE_PATH%"
)
@IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.exe"  "%~dp0\..\eslint\bin\eslint.js" %*
) ELSE (
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  node  "%~dp0\..\eslint\bin\eslint.js" %*
)
#!/usr/bin/env pwsh
$basedir=Split-Path $MyInvocation.MyCommand.Definition -Parent

$exe=""
$pathsep=":"
$env_node_path=$env:NODE_PATH
$new_node_path="C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\eslint@8.57.1\node_modules\eslint\bin\node_modules;C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\eslint@8.57.1\node_modules\eslint\node_modules;C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\eslint@8.57.1\node_modules;C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\node_modules"
if ($PSVersionTable.PSVersion -lt "6.0" -or $IsWindows) {
  # Fix case when both the Windows and Linux builds of Node
  # are installed in the same directory
  $exe=".exe"
  $pathsep=";"
} else {
  $new_node_path="/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/eslint@8.57.1/node_modules/eslint/bin/node_modules:/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/eslint@8.57.1/node_modules/eslint/node_modules:/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/eslint@8.57.1/node_modules:/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/node_modules"
}
if ([string]::IsNullOrEmpty($env_node_path)) {
  $env:NODE_PATH=$new_node_path
} else {
  $env:NODE_PATH="$new_node_path$pathsep$env_node_path"
}

$ret=0
if (Test-Path "$basedir/node$exe") {
  # Support pipeline input
  if ($MyInvocation.ExpectingInput) {
    $input | & "$basedir/node$exe"  "$basedir/../eslint/bin/eslint.js" $args
  } else {
    & "$basedir/node$exe"  "$basedir/../eslint/bin/eslint.js" $args
  }
  $ret=$LASTEXITCODE
} else {
  # Support pipeline input
  if ($MyInvocation.ExpectingInput) {
    $input | & "node$exe"  "$basedir/../eslint/bin/eslint.js" $args
  } else {
    & "node$exe"  "$basedir/../eslint/bin/eslint.js" $args
  }
  $ret=$LASTEXITCODE
}
$env:NODE_PATH=$env_node_path
exit $ret
#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/tailwindcss@3.4.19_tsx@4.23.0/node_modules/tailwindcss/lib/node_modules:/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/tailwindcss@3.4.19_tsx@4.23.0/node_modules/tailwindcss/node_modules:/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/tailwindcss@3.4.19_tsx@4.23.0/node_modules:/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/node_modules"
else
  export NODE_PATH="/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/tailwindcss@3.4.19_tsx@4.23.0/node_modules/tailwindcss/lib/node_modules:/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/tailwindcss@3.4.19_tsx@4.23.0/node_modules/tailwindcss/node_modules:/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/tailwindcss@3.4.19_tsx@4.23.0/node_modules:/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../tailwindcss/lib/cli.js" "$@"
else
  exec node  "$basedir/../tailwindcss/lib/cli.js" "$@"
fi
@SETLOCAL
@IF NOT DEFINED NODE_PATH (
  @SET "NODE_PATH=C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\tailwindcss@3.4.19_tsx@4.23.0\node_modules\tailwindcss\lib\node_modules;C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\tailwindcss@3.4.19_tsx@4.23.0\node_modules\tailwindcss\node_modules;C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\tailwindcss@3.4.19_tsx@4.23.0\node_modules;C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\node_modules"
) ELSE (
  @SET "NODE_PATH=C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\tailwindcss@3.4.19_tsx@4.23.0\node_modules\tailwindcss\lib\node_modules;C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\tailwindcss@3.4.19_tsx@4.23.0\node_modules\tailwindcss\node_modules;C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\tailwindcss@3.4.19_tsx@4.23.0\node_modules;C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\node_modules;%NODE_PATH%"
)
@IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.exe"  "%~dp0\..\tailwindcss\lib\cli.js" %*
) ELSE (
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  node  "%~dp0\..\tailwindcss\lib\cli.js" %*
)
#!/usr/bin/env pwsh
$basedir=Split-Path $MyInvocation.MyCommand.Definition -Parent

$exe=""
$pathsep=":"
$env_node_path=$env:NODE_PATH
$new_node_path="C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\tailwindcss@3.4.19_tsx@4.23.0\node_modules\tailwindcss\lib\node_modules;C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\tailwindcss@3.4.19_tsx@4.23.0\node_modules\tailwindcss\node_modules;C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\tailwindcss@3.4.19_tsx@4.23.0\node_modules;C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\node_modules"
if ($PSVersionTable.PSVersion -lt "6.0" -or $IsWindows) {
  # Fix case when both the Windows and Linux builds of Node
  # are installed in the same directory
  $exe=".exe"
  $pathsep=";"
} else {
  $new_node_path="/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/tailwindcss@3.4.19_tsx@4.23.0/node_modules/tailwindcss/lib/node_modules:/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/tailwindcss@3.4.19_tsx@4.23.0/node_modules/tailwindcss/node_modules:/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/tailwindcss@3.4.19_tsx@4.23.0/node_modules:/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/node_modules"
}
if ([string]::IsNullOrEmpty($env_node_path)) {
  $env:NODE_PATH=$new_node_path
} else {
  $env:NODE_PATH="$new_node_path$pathsep$env_node_path"
}

$ret=0
if (Test-Path "$basedir/node$exe") {
  # Support pipeline input
  if ($MyInvocation.ExpectingInput) {
    $input | & "$basedir/node$exe"  "$basedir/../tailwindcss/lib/cli.js" $args
  } else {
    & "$basedir/node$exe"  "$basedir/../tailwindcss/lib/cli.js" $args
  }
  $ret=$LASTEXITCODE
} else {
  # Support pipeline input
  if ($MyInvocation.ExpectingInput) {
    $input | & "node$exe"  "$basedir/../tailwindcss/lib/cli.js" $args
  } else {
    & "node$exe"  "$basedir/../tailwindcss/lib/cli.js" $args
  }
  $ret=$LASTEXITCODE
}
$env:NODE_PATH=$env_node_path
exit $ret
#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/tailwindcss@3.4.19_tsx@4.23.0/node_modules/tailwindcss/lib/node_modules:/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/tailwindcss@3.4.19_tsx@4.23.0/node_modules/tailwindcss/node_modules:/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/tailwindcss@3.4.19_tsx@4.23.0/node_modules:/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/node_modules"
else
  export NODE_PATH="/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/tailwindcss@3.4.19_tsx@4.23.0/node_modules/tailwindcss/lib/node_modules:/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/tailwindcss@3.4.19_tsx@4.23.0/node_modules/tailwindcss/node_modules:/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/tailwindcss@3.4.19_tsx@4.23.0/node_modules:/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../tailwindcss/lib/cli.js" "$@"
else
  exec node  "$basedir/../tailwindcss/lib/cli.js" "$@"
fi
@SETLOCAL
@IF NOT DEFINED NODE_PATH (
  @SET "NODE_PATH=C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\tailwindcss@3.4.19_tsx@4.23.0\node_modules\tailwindcss\lib\node_modules;C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\tailwindcss@3.4.19_tsx@4.23.0\node_modules\tailwindcss\node_modules;C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\tailwindcss@3.4.19_tsx@4.23.0\node_modules;C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\node_modules"
) ELSE (
  @SET "NODE_PATH=C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\tailwindcss@3.4.19_tsx@4.23.0\node_modules\tailwindcss\lib\node_modules;C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\tailwindcss@3.4.19_tsx@4.23.0\node_modules\tailwindcss\node_modules;C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\tailwindcss@3.4.19_tsx@4.23.0\node_modules;C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\node_modules;%NODE_PATH%"
)
@IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.exe"  "%~dp0\..\tailwindcss\lib\cli.js" %*
) ELSE (
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  node  "%~dp0\..\tailwindcss\lib\cli.js" %*
)
#!/usr/bin/env pwsh
$basedir=Split-Path $MyInvocation.MyCommand.Definition -Parent

$exe=""
$pathsep=":"
$env_node_path=$env:NODE_PATH
$new_node_path="C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\tailwindcss@3.4.19_tsx@4.23.0\node_modules\tailwindcss\lib\node_modules;C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\tailwindcss@3.4.19_tsx@4.23.0\node_modules\tailwindcss\node_modules;C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\tailwindcss@3.4.19_tsx@4.23.0\node_modules;C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\node_modules"
if ($PSVersionTable.PSVersion -lt "6.0" -or $IsWindows) {
  # Fix case when both the Windows and Linux builds of Node
  # are installed in the same directory
  $exe=".exe"
  $pathsep=";"
} else {
  $new_node_path="/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/tailwindcss@3.4.19_tsx@4.23.0/node_modules/tailwindcss/lib/node_modules:/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/tailwindcss@3.4.19_tsx@4.23.0/node_modules/tailwindcss/node_modules:/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/tailwindcss@3.4.19_tsx@4.23.0/node_modules:/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/node_modules"
}
if ([string]::IsNullOrEmpty($env_node_path)) {
  $env:NODE_PATH=$new_node_path
} else {
  $env:NODE_PATH="$new_node_path$pathsep$env_node_path"
}

$ret=0
if (Test-Path "$basedir/node$exe") {
  # Support pipeline input
  if ($MyInvocation.ExpectingInput) {
    $input | & "$basedir/node$exe"  "$basedir/../tailwindcss/lib/cli.js" $args
  } else {
    & "$basedir/node$exe"  "$basedir/../tailwindcss/lib/cli.js" $args
  }
  $ret=$LASTEXITCODE
} else {
  # Support pipeline input
  if ($MyInvocation.ExpectingInput) {
    $input | & "node$exe"  "$basedir/../tailwindcss/lib/cli.js" $args
  } else {
    & "node$exe"  "$basedir/../tailwindcss/lib/cli.js" $args
  }
  $ret=$LASTEXITCODE
}
$env:NODE_PATH=$env_node_path
exit $ret
#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/typescript@5.9.3/node_modules/typescript/bin/node_modules:/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/typescript@5.9.3/node_modules/typescript/node_modules:/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/typescript@5.9.3/node_modules:/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/node_modules"
else
  export NODE_PATH="/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/typescript@5.9.3/node_modules/typescript/bin/node_modules:/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/typescript@5.9.3/node_modules/typescript/node_modules:/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/typescript@5.9.3/node_modules:/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../typescript/bin/tsc" "$@"
else
  exec node  "$basedir/../typescript/bin/tsc" "$@"
fi
@SETLOCAL
@IF NOT DEFINED NODE_PATH (
  @SET "NODE_PATH=C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\typescript@5.9.3\node_modules\typescript\bin\node_modules;C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\typescript@5.9.3\node_modules\typescript\node_modules;C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\typescript@5.9.3\node_modules;C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\node_modules"
) ELSE (
  @SET "NODE_PATH=C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\typescript@5.9.3\node_modules\typescript\bin\node_modules;C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\typescript@5.9.3\node_modules\typescript\node_modules;C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\typescript@5.9.3\node_modules;C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\node_modules;%NODE_PATH%"
)
@IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.exe"  "%~dp0\..\typescript\bin\tsc" %*
) ELSE (
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  node  "%~dp0\..\typescript\bin\tsc" %*
)
#!/usr/bin/env pwsh
$basedir=Split-Path $MyInvocation.MyCommand.Definition -Parent

$exe=""
$pathsep=":"
$env_node_path=$env:NODE_PATH
$new_node_path="C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\typescript@5.9.3\node_modules\typescript\bin\node_modules;C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\typescript@5.9.3\node_modules\typescript\node_modules;C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\typescript@5.9.3\node_modules;C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\node_modules"
if ($PSVersionTable.PSVersion -lt "6.0" -or $IsWindows) {
  # Fix case when both the Windows and Linux builds of Node
  # are installed in the same directory
  $exe=".exe"
  $pathsep=";"
} else {
  $new_node_path="/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/typescript@5.9.3/node_modules/typescript/bin/node_modules:/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/typescript@5.9.3/node_modules/typescript/node_modules:/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/typescript@5.9.3/node_modules:/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/node_modules"
}
if ([string]::IsNullOrEmpty($env_node_path)) {
  $env:NODE_PATH=$new_node_path
} else {
  $env:NODE_PATH="$new_node_path$pathsep$env_node_path"
}

$ret=0
if (Test-Path "$basedir/node$exe") {
  # Support pipeline input
  if ($MyInvocation.ExpectingInput) {
    $input | & "$basedir/node$exe"  "$basedir/../typescript/bin/tsc" $args
  } else {
    & "$basedir/node$exe"  "$basedir/../typescript/bin/tsc" $args
  }
  $ret=$LASTEXITCODE#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/typescript@5.9.3/node_modules/typescript/bin/node_modules:/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/typescript@5.9.3/node_modules/typescript/node_modules:/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/typescript@5.9.3/node_modules:/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/node_modules"
else
  export NODE_PATH="/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/typescript@5.9.3/node_modules/typescript/bin/node_modules:/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/typescript@5.9.3/node_modules/typescript/node_modules:/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/typescript@5.9.3/node_modules:/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../typescript/bin/tsserver" "$@"
else
  exec node  "$basedir/../typescript/bin/tsserver" "$@"
fi
@SETLOCAL
@IF NOT DEFINED NODE_PATH (
  @SET "NODE_PATH=C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\typescript@5.9.3\node_modules\typescript\bin\node_modules;C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\typescript@5.9.3\node_modules\typescript\node_modules;C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\typescript@5.9.3\node_modules;C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\node_modules"
) ELSE (
  @SET "NODE_PATH=C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\typescript@5.9.3\node_modules\typescript\bin\node_modules;C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\typescript@5.9.3\node_modules\typescript\node_modules;C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\typescript@5.9.3\node_modules;C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\node_modules;%NODE_PATH%"
)
@IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.exe"  "%~dp0\..\typescript\bin\tsserver" %*
) ELSE (
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  node  "%~dp0\..\typescript\bin\tsserver" %*
)
#!/usr/bin/env pwsh
$basedir=Split-Path $MyInvocation.MyCommand.Definition -Parent

$exe=""
$pathsep=":"
$env_node_path=$env:NODE_PATH
$new_node_path="C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\typescript@5.9.3\node_modules\typescript\bin\node_modules;C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\typescript@5.9.3\node_modules\typescript\node_modules;C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\typescript@5.9.3\node_modules;C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\node_modules"
if ($PSVersionTable.PSVersion -lt "6.0" -or $IsWindows) {
  # Fix case when both the Windows and Linux builds of Node
  # are installed in the same directory
  $exe=".exe"
  $pathsep=";"
} else {
  $new_node_path="/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/typescript@5.9.3/node_modules/typescript/bin/node_modules:/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/typescript@5.9.3/node_modules/typescript/node_modules:/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/typescript@5.9.3/node_modules:/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/node_modules"
}
if ([string]::IsNullOrEmpty($env_node_path)) {
  $env:NODE_PATH=$new_node_path
} else {
  $env:NODE_PATH="$new_node_path$pathsep$env_node_path"
}

$ret=0
if (Test-Path "$basedir/node$exe") {
  # Support pipeline input
  if ($MyInvocation.ExpectingInput) {
    $input | & "$basedir/node$exe"  "$basedir/../typescript/bin/tsserver" $args
  } else {
    & "$basedir/node$exe"  "$basedir/../typescript/bin/tsserver" $args
  }
  $ret=$LASTEXITCODE
} else {
  # Support pipeline input
  if ($MyInvocation.ExpectingInput) {
    $input | & "node$exe"  "$basedir/../typescript/bin/tsserver" $args
  } else {
    & "node$exe"  "$basedir/../typescript/bin/tsserver" $args
  }
  $ret=$LASTEXITCODE
}
$env:NODE_PATH=$env_node_path
exit $ret

} else {
  # Support pipeline input
  if ($MyInvocation.ExpectingInput) {
    $input | & "node$exe"  "$basedir/../typescript/bin/tsc" $args
  } else {
    & "node$exe"  "$basedir/../typescript/bin/tsc" $args
  }
  $ret=$LASTEXITCODE
}
$env:NODE_PATH=$env_node_path
exit $ret
#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/vite@5.4.21_@types+node@20.19.43/node_modules/vite/bin/node_modules:/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/vite@5.4.21_@types+node@20.19.43/node_modules/vite/node_modules:/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/vite@5.4.21_@types+node@20.19.43/node_modules:/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/node_modules"
else
  export NODE_PATH="/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/vite@5.4.21_@types+node@20.19.43/node_modules/vite/bin/node_modules:/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/vite@5.4.21_@types+node@20.19.43/node_modules/vite/node_modules:/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/vite@5.4.21_@types+node@20.19.43/node_modules:/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../vite/bin/vite.js" "$@"
else
  exec node  "$basedir/../vite/bin/vite.js" "$@"
fi
@SETLOCAL
@IF NOT DEFINED NODE_PATH (
  @SET "NODE_PATH=C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\vite@5.4.21_@types+node@20.19.43\node_modules\vite\bin\node_modules;C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\vite@5.4.21_@types+node@20.19.43\node_modules\vite\node_modules;C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\vite@5.4.21_@types+node@20.19.43\node_modules;C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\node_modules"
) ELSE (
  @SET "NODE_PATH=C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\vite@5.4.21_@types+node@20.19.43\node_modules\vite\bin\node_modules;C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\vite@5.4.21_@types+node@20.19.43\node_modules\vite\node_modules;C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\vite@5.4.21_@types+node@20.19.43\node_modules;C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\node_modules;%NODE_PATH%"
)
@IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.exe"  "%~dp0\..\vite\bin\vite.js" %*
) ELSE (
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  node  "%~dp0\..\vite\bin\vite.js" %*
)
#!/usr/bin/env pwsh
$basedir=Split-Path $MyInvocation.MyCommand.Definition -Parent

$exe=""
$pathsep=":"
$env_node_path=$env:NODE_PATH
$new_node_path="C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\vite@5.4.21_@types+node@20.19.43\node_modules\vite\bin\node_modules;C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\vite@5.4.21_@types+node@20.19.43\node_modules\vite\node_modules;C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\vite@5.4.21_@types+node@20.19.43\node_modules;C:\Users\win11\Desktop\CSFAQ-NEW\CSFAQ-NEW\node_modules\.pnpm\node_modules"
if ($PSVersionTable.PSVersion -lt "6.0" -or $IsWindows) {
  # Fix case when both the Windows and Linux builds of Node
  # are installed in the same directory
  $exe=".exe"
  $pathsep=";"
} else {
  $new_node_path="/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/vite@5.4.21_@types+node@20.19.43/node_modules/vite/bin/node_modules:/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/vite@5.4.21_@types+node@20.19.43/node_modules/vite/node_modules:/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/vite@5.4.21_@types+node@20.19.43/node_modules:/mnt/c/Users/win11/Desktop/CSFAQ-NEW/CSFAQ-NEW/node_modules/.pnpm/node_modules"
}
if ([string]::IsNullOrEmpty($env_node_path)) {
  $env:NODE_PATH=$new_node_path
} else {
  $env:NODE_PATH="$new_node_path$pathsep$env_node_path"
}

$ret=0
if (Test-Path "$basedir/node$exe") {
  # Support pipeline input
  if ($MyInvocation.ExpectingInput) {
    $input | & "$basedir/node$exe"  "$basedir/../vite/bin/vite.js" $args
  } else {
    & "$basedir/node$exe"  "$basedir/../vite/bin/vite.js" $args
  }
  $ret=$LASTEXITCODE
} else {
  # Support pipeline input
  if ($MyInvocation.ExpectingInput) {
    $input | & "node$exe"  "$basedir/../vite/bin/vite.js" $args
  } else {
    & "node$exe"  "$basedir/../vite/bin/vite.js" $args
  }
  $ret=$LASTEXITCODE
}
$env:NODE_PATH=$env_node_path
exit $ret
